version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "America/New_York"
    open-pull-requests-limit: 0
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  # Frontend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
      timezone: "America/New_York"
    open-pull-requests-limit: 0
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      frontend-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
      timezone: "America/New_York"
    open-pull-requests-limit: 0
    groups:
      docker-images:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "America/New_York"
    open-pull-requests-limit: 0
    groups:
      github-actions:
        patterns:
          - "*"