# Generated by Django 5.0.6 on 2024-07-15 12:00

from django.db import migrations

def add_hls_proxy_data(apps, schema_editor):
    """
    Adds the 'HLS Proxy' StreamProfile and related CoreSettings.
    """
    StreamProfile = apps.get_model('core', 'StreamProfile')
    CoreSettings = apps.get_model('core', 'CoreSettings')
    UserAgent = apps.get_model('core', 'UserAgent')

    # Get a default UserAgent (or create one if none exist)
    # This is to ensure the StreamProfile has a valid UserAgent
    user_agent, _ = UserAgent.objects.get_or_create(
        name="Default FFmpeg",
        user_agent_string="Lavf/58.29.100" # A common FFmpeg user agent
    )

    # Add HLS Proxy StreamProfile
    StreamProfile.objects.create(
        name="HLS Proxy",
        command="ffmpeg",
        parameters="-i {streamUrl} -user_agent \"{userAgent}\" -f hls",
        locked=True,
        is_active=True,
        default_user_agent=user_agent # Associate the UserAgent
    )

    # Add CoreSettings for HLS
    core_settings_data = [
        {
            "key": "hls_segment_path",
            "name": "HLS Segment Path",
            "value": "/opt/dispatcharr/hls/",
            "description": "Path where HLS segments will be stored.",
            "field_type": "text",
            "is_public": True,
        },
        {
            "key": "hls_default_segment_time",
            "name": "HLS Default Segment Time",
            "value": "4",
            "description": "Default duration for HLS segments in seconds.",
            "field_type": "number",
            "is_public": True,
        },
        {
            "key": "hls_default_list_size",
            "name": "HLS Default List Size",
            "value": "5",
            "description": "Default number of segments in HLS playlist.",
            "field_type": "number",
            "is_public": True,
        },
        {
            "key": "hls_default_flags",
            "name": "HLS Default Flags",
            "value": "delete_segments+round_durations",
            "description": "Default HLS flags for FFmpeg (e.g., delete_segments, round_durations).",
            "field_type": "text",
            "is_public": True,
        },
        {
            "key": "hls_extra_ffmpeg_options",
            "name": "HLS Extra FFmpeg Options",
            "value": "",
            "description": "Extra FFmpeg options for HLS streams (applied globally).",
            "field_type": "text",
            "is_public": True,
        },
    ]

    for setting_data in core_settings_data:
        CoreSettings.objects.update_or_create(
            key=setting_data["key"],
            defaults=setting_data
        )

def remove_hls_proxy_data(apps, schema_editor):
    """
    Removes the 'HLS Proxy' StreamProfile and related CoreSettings.
    (Optional: Implement if rollback is needed)
    """
    StreamProfile = apps.get_model('core', 'StreamProfile')
    CoreSettings = apps.get_model('core', 'CoreSettings')

    StreamProfile.objects.filter(name="HLS Proxy").delete()
    CoreSettings.objects.filter(
        key__in=[
            "hls_segment_path",
            "hls_default_segment_time",
            "hls_default_list_size",
            "hls_default_flags",
            "hls_extra_ffmpeg_options",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_default_proxy_settings'), # Adjust if your previous migration is different
    ]

    operations = [
        migrations.RunPython(add_hls_proxy_data, reverse_code=remove_hls_proxy_data),
    ]
