# Generated by Django 5.0.6 on 2024-06-21 06:42

from django.db import migrations

HLS_ABR_RENDITIONS_KEY = "hls_abr_renditions"
HLS_ABR_RENDITIONS_NAME = "HLS ABR Renditions"
HLS_ABR_RENDITIONS_DEFAULT_VALUE = "[]" # JSON string for an empty list
HLS_ABR_RENDITIONS_DESCRIPTION = (
    "JSON array defining ABR renditions. Each object specifies name, height, "
    "bitrate_video, bitrate_audio, ffmpeg_opts. Example: "
    '[{"name": "720p", "height": 720, "bitrate_video": "2000k", ...}]'
)
# The CoreSettings model does not have description, field_type, is_public fields.
# These were intended for a more complex model. We will only use key, name, value.

def add_abr_setting(apps, schema_editor):
    CoreSettings = apps.get_model('core', 'CoreSettings')
    CoreSettings.objects.update_or_create(
        key=HLS_ABR_RENDITIONS_KEY,
        defaults={
            "name": HLS_ABR_RENDITIONS_NAME,
            "value": HLS_ABR_RENDITIONS_DEFAULT_VALUE,
            # No 'description', 'field_type', 'is_public' as they don't exist on the model
        }
    )

def remove_abr_setting(apps, schema_editor):
    CoreSettings = apps.get_model('core', 'CoreSettings')
    CoreSettings.objects.filter(key=HLS_ABR_RENDITIONS_KEY).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_hls_proxy_settings'),
    ]

    operations = [
        migrations.RunPython(add_abr_setting, reverse_code=remove_abr_setting),
    ]
