# Generated by Django 6.0.6 on 2026-07-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0004_m3uepisoderelation_series_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vodlogo',
            name='name',
            field=models.TextField(),
        ),
    ]
