# Generated by Django 6.0.8 on 2026-09-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0005_movie_is_adult'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movie',
            name='unique_movie_name_year_no_external_id',
        ),
        migrations.RemoveConstraint(
            model_name='series',
            name='unique_series_name_year_no_external_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 639-1 language assigned by the source category; empty when untagged', max_length=2),
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 639-1 language assigned by the source category; empty when untagged', max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, help_text='IMDB ID for metadata', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, db_index=True, help_text='TMDB ID for metadata', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, help_text='IMDB ID for metadata', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tmdb_id',
            field=models.CharField(blank=True, db_index=True, help_text='TMDB ID for metadata', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', False)), fields=('tmdb_id', 'language'), name='unique_movie_tmdb_id_language'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(condition=models.Q(('imdb_id__isnull', False)), fields=('imdb_id', 'language'), name='unique_movie_imdb_id_language'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', True), ('imdb_id__isnull', True)), fields=('name', 'year', 'language'), name='unique_movie_name_year_language_no_external_id'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', False)), fields=('tmdb_id', 'language'), name='unique_series_tmdb_id_language'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(condition=models.Q(('imdb_id__isnull', False)), fields=('imdb_id', 'language'), name='unique_series_imdb_id_language'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(condition=models.Q(('tmdb_id__isnull', True), ('imdb_id__isnull', True)), fields=('name', 'year', 'language'), name='unique_series_name_year_language_no_external_id'),
        ),
    ]
