# Generated by Django 5.2.4 on 2025-11-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0030_alter_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ForeignKey(
                blank=True,
                help_text='Custom banner image for program listings',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='channels',
                to='dispatcharr_channels.banner'
            ),
        ),
        migrations.AddField(
            model_name='channel',
            name='convert_banner_to_portrait',
            field=models.BooleanField(
                default=False,
                help_text='Convert banner to portrait format (2:3 aspect ratio) with blurred background'
            ),
        ),
    ]
