# Generated by Django 6.0.6 on 2026-07-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0038_add_catchup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.TextField(),
        ),
    ]
