# Generated by Django 6.0.7 on 2026-08-13 15:56

import apps.mac_panel.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacPanelDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('iboxx', 'IBOXX Player'), ('cr7', 'CR7 Player')], max_length=32)),
                ('panel_base_url', models.CharField(blank=True, default='', help_text='Override the registry base URL for this panel (e.g. a sibling domain).', max_length=255)),
                ('mac_address', models.CharField(max_length=17, validators=[apps.mac_panel.models.validate_mac_address])),
                ('device_key', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('playlist_name', models.CharField(default='Dispatcharr', max_length=100)),
                ('include_epg', models.BooleanField(default=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_push_message', models.TextField(blank=True, default='')),
                ('last_playlist_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('panel', 'mac_address')},
            },
        ),
    ]
