# Generated by Django 6.0.7 on 2026-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macpaneldevice',
            name='panel',
            field=models.CharField(choices=[('iboxx', 'IBOXX Player'), ('cr7', 'CR7 Player'), ('iboplayer', 'IBO Player'), ('ibovpn', 'IBO VPN Player'), ('messitv', 'Messi TV Player'), ('hqplayer', 'HQ Player TV')], max_length=32),
        ),
    ]
