# Generated by Django 6.0.7 on 2026-08-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_panel', '0002_alter_macpaneldevice_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='macpaneldevice',
            name='protect_pin',
            field=models.CharField(blank=True, default='', help_text="Optional PIN to protect the pushed playlist on the panel side (mirrors the panel's own 'Protect Playlist' option). Blank = not protected.", max_length=20),
        ),
    ]
