# Generated by Django 5.1.4 on 2025-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0015_add_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgdata',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Logo URL from Schedules Direct or other EPG source', null=True),
        ),
        migrations.AlterField(
            model_name='epgsource',
            name='username',
            field=models.CharField(blank=True, help_text='For Schedules Direct username', max_length=255, null=True),
        ),
    ]